Repository cat2k22/Hacktoberfest2022, pull requests merged in 2022-10, with the labels that each got.

#12 Animation Login page
  Weather/index.html
  index.html
  style.css
Labels: enhancement, good first issue, hacktoberfest2022, hacktoberfest-accepted, hacktoberfest, Medium

#14 Create form.html
  Form with validation/form.html
Labels: enhancement, good first issue, hacktoberfest2022, hacktoberfest-accepted, hacktoberfest, Medium

#15 weather- app
  Weather-app/index.html
Labels: enhancement, good first issue, hacktoberfest2022, hacktoberfest-accepted, hacktoberfest

#16 Simple web page
  Simple Web page/bg.php
  Simple Web page/del.php
  Simple Web page/delete.html
  Simple Web page/edit.php
  Simple Web page/log.html
  Simple Web page/reg.php
  Simple Web page/se.html
  Simple Web page/search.php
  Simple Web page/up.html
  Simple Web page/up.php
  Simple Web page/update.php
Labels: enhancement, good first issue, hacktoberfest2022, hacktoberfest-accepted, hacktoberfest, easy

#18 Login-page validation
  Login-page validation/index.html
  Login-page validation/script.js
  Login-page validation/style.css
Labels: enhancement, good first issue, hacktoberfest2022, hacktoberfest-accepted, hacktoberfest, easy

#22 Countdowntimer
  CountdownTimer
Labels: enhancement, good first issue, hacktoberfest2022, hacktoberfest-accepted, hacktoberfest, Medium

#29 program for a simple calculator is added
  simple_calculator.cpp
  simple_calculator.exe
Labels: enhancement, good first issue, hacktoberfest2022, hacktoberfest-accepted, hacktoberfest, Medium

#32 Update index.html
  Animated-login/index.html
Labels: hacktoberfest2022, hacktoberfest-accepted, hacktoberfest

#33 Create SECURITY.md
  SECURITY.md
Labels: hacktoberfest2022, hacktoberfest-accepted, hacktoberfest

#34 Update README.md
  README.md
Labels: documentation, enhancement, good first issue, hacktoberfest2022, hacktoberfest-accepted, hacktoberfest

#42 Simple Racing Game
  Simple Racing Game
Labels: enhancement, good first issue, hacktoberfest2022, hacktoberfest-accepted, hacktoberfest, Medium

#49 Updated index.html
  index.html
Labels: good first issue, hacktoberfest2022, hacktoberfest-accepted, hacktoberfest

#50 added the snake game #10
  Snakegame.html
Labels: enhancement, good first issue, hacktoberfest2022, hacktoberfest-accepted, hacktoberfest, Medium

#52 Update Snakegame.html
  Snakegame.html
Labels: documentation, enhancement, good first issue, hacktoberfest2022, hacktoberfest-accepted, hacktoberfest, easy, bug-fixes
